In [33]:
import numpy as np
y_true = np.array([1,0,2,1,1,2,0,1,2,1])
y_pred = np.array([1,2,0,1,0,2,0,1,1,1])

In [63]:
import numpy as np

def confusion_matrix(y_true, y_pred,normalize=None):
    """Computes the confusion matrix from predictions and labels.

    The matrix columns represent the real labels and the rows represent the
    prediction labels. The confusion matrix is always a 2-D array of shape `[n_labels, n_labels]`,
    where `n_labels` is the number of valid labels for a given classification task. Both
    prediction and labels must be 1-D arrays of the same shape in order for this
    function to work.

    Parameters:
        y_true: 1-D array of real labels for the classification task.
        y_pred: 1-D array of predictions for a given classification.
        normalize: One of ['true', 'pred', 'all', None], corresponding to column sum, row sum, matrix sum, or no
                   normalization.

    Returns:
        A 2-D array with shape `[n_labels, n_labels]` representing the confusion
        matrix, where `n` is the number of possible labels in the classification
        task.
    """
    x = y_true
    y = y_pred
    N_ele = np.unique(x)
    N_Len = len(N_ele)
    cm = np.zeros((N_Len,1))
    
    for i in range(N_Len):
        temp = y[x==N_ele[i]]
        emt_hist = np.zeros((N_Len,1))
        Hist = np.asarray(np.unique(temp, return_counts=True)).T
        temp_hist_r1 = Hist[:,0].reshape((len(Hist[:,0]), 1))
        temp_hist_r2 = Hist[:,1].reshape((len(Hist[:,0]), 1))
        emt_hist[temp_hist_r1[:,0]] = temp_hist_r2
        emt_hist = emt_hist.reshape((len(emt_hist), 1))
        cm = np.hstack((cm, emt_hist))

    cm = np.delete(cm, 0, axis=1)
    cm = np.transpose(cm)

    if normalize not in ['true', 'pred', 'all', None]:
        raise ValueError("normalize must be one of {'true', 'pred', 'all', None}")

    if normalize == 'true':
        cm = cm / cm.sum(axis=1, keepdims=True)
    elif normalize == 'pred':
        cm = cm / cm.sum(axis=0, keepdims=True)
    elif normalize == 'all':
        cm = cm / cm.sum()
        # TODO (TASK 1)

    return cm


def precision(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred,normalize='pred')
    p = cm.diagonal()
    return p
    # TODO (TASK 2)


def recall(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred,normalize='true')
    r = cm.diagonal()
    return r
    # TODO (TASK 2)


def false_alarm_rate(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred,normalize='all')
    
    FP = cm.sum(axis=0) - np.diag(cm)  
    #FN = cm.sum(axis=1) - np.diag(cm)
    TP = np.diag(cm)
    #TN = cm.sum() - (FP + FN + TP)
    
    FAR = FP/(TP+FP)
    return FP/(TP+FP)


In [64]:
print(y_true,'\n', y_pred)


false_alarm_rate(y_true, y_pred)


[0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 0] 
 [1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 0 0 0]


array([0.43, 0.69])

In [66]:
from metrics import confusion_matrix, precision, recall, false_alarm_rate
np.random.seed(42)
np.set_printoptions(precision=2, floatmode='fixed')

 # Part I
print("------------------------------------------------")
print("Part I - Confusion matrix")
print("------------------------------------------------")

y_true = np.random.randint(0, 2, 20)
y_pred = np.random.randint(0, 2, 20)

print("Unnormalized confusion matrix:")
cm = confusion_matrix(y_true, y_pred)
print(cm)
print("Matrix sum normalization:")
cm = confusion_matrix(y_true, y_pred, normalize='all')
print(cm)
print("Row sum normalization:")
cm = confusion_matrix(y_true, y_pred, normalize='pred')
print(cm)
print("Column sum normalization:")
cm = confusion_matrix(y_true, y_pred, normalize='true')
print(cm)
false_alarm_rate(y_true, y_pred)
print('Precision:' , precision(y_true, y_pred), '\nRecall:',recall(y_true, y_pred), '\nFalse alarm rate:', false_alarm_rate(y_true, y_pred))

------------------------------------------------
Part I - Confusion matrix
------------------------------------------------
Unnormalized confusion matrix:
[[4.00 9.00]
 [3.00 4.00]]
Matrix sum normalization:
[[0.20 0.45]
 [0.15 0.20]]
Row sum normalization:
[[0.57 0.69]
 [0.43 0.31]]
Column sum normalization:
[[0.31 0.69]
 [0.43 0.57]]
Precision: [0.57 0.31] 
Recall: [0.31 0.57] 
False alarm rate: None


In [67]:
print(confusion_matrix(y_true,y_pred))
print(precision(y_true,y_pred))
print(recall(y_true,y_pred))
print(false_alarm_rate(y_true, y_pred))
#print(confusion_matrix(y_true, y_pred,normalize='true'))
#print(confusion_matrix(y_true, y_pred,normalize='pred'))
#print(confusion_matrix(y_true, y_pred,normalize='all'))
#print(confusion_matrix(y_true, y_pred,normalize=None))

[[4.00 9.00]
 [3.00 4.00]]
[0.57 0.31]
[0.31 0.57]
None


In [27]:


#Using your data, you can get all the metrics for all the classes at once:

import numpy as np
from sklearn.metrics import confusion_matrix

y_true = y_true
y_prediction = y_pred
cnf_matrix = confusion_matrix(y_true, y_prediction)
print(cnf_matrix)
#[[1 1 3]
# [3 2 2]
# [1 3 1]]

FP = cnf_matrix.sum(axis=0) - np.diag(cnf_matrix)  
FN = cnf_matrix.sum(axis=1) - np.diag(cnf_matrix)
TP = np.diag(cnf_matrix)
TN = cnf_matrix.sum() - (FP + FN + TP)

FP = FP.astype(float)
FN = FN.astype(float)
TP = TP.astype(float)
TN = TN.astype(float)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)
# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)


#rint(TNR)
print(PPV)
print(TPR)
#rint(NPV)
#rint(FPR)
#rint(FNR)
print(FDR)
#rint(ACC)


[[4 9]
 [3 4]]
[0.57 0.31]
[0.31 0.57]
[0.43 0.69]


In [28]:
from sklearn.metrics import confusion_matrix
import numpy as np
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score


print(recall_score(y_true, y_pred, average='macro'))
print(precision_score(y_true, y_pred, average='micro'))
print(precision_score(y_true, y_pred, average='weighted'))
print(precision_score(y_true, y_pred, average=None))
print(recall_score(y_true, y_pred, average=None))
print(precision_score(y_true, y_pred, average=None, zero_division=1))

0.43956043956043955
0.4
0.4791208791208791
[0.57 0.31]
[0.31 0.57]
[0.57 0.31]


In [29]:
confusion_matrix(y_true, y_pred,normalize=None)

array([[4, 9],
       [3, 4]], dtype=int64)

In [31]:
%run metrics.py

In [32]:
# %load main.py
import numpy as np

from metrics import confusion_matrix, precision, recall, false_alarm_rate
from datasets import download_and_prepare
from recommender_system import MatrixFactorization


def main():
    np.random.seed(42)
    np.set_printoptions(precision=2, floatmode='fixed')

    # Part I
    print("------------------------------------------------")
    print("Part I - Confusion matrix")
    print("------------------------------------------------")

    y_true = np.random.randint(0, 2, 20)
    y_pred = np.random.randint(0, 2, 20)

    print("Unnormalized confusion matrix:")
    cm = confusion_matrix(y_true, y_pred)
    print(cm)
    print("Matrix sum normalization:")
    cm = confusion_matrix(y_true, y_pred, normalize='all')
    print(cm)
    print("Row sum normalization:")
    cm = confusion_matrix(y_true, y_pred, normalize='pred')
    print(cm)
    print("Column sum normalization:")
    cm = confusion_matrix(y_true, y_pred, normalize='true')
    print(cm)
    print(f"Precision: {precision(y_true, y_pred):.2f}, recall: {recall(y_true, y_pred):.2f}"
          f", false alarm rate: {false_alarm_rate(y_true, y_pred):.2f}")

    # Part II
    print("------------------------------------------------")
    print("Part II - Movie Recommender System")
    print("------------------------------------------------")

    X = download_and_prepare('movielens-small', '../datasets')
    matrixFactor = MatrixFactorization(X)
    r_hat = matrixFactor.fit()

if __name__ == "__main__":
    main()


SyntaxError: invalid syntax (recommender_system.py, line 19)

In [34]:
%run main.py

SyntaxError: invalid syntax (recommender_system.py, line 19)